### ISSUE TITLE
Can't do more than one http call on a program

### ISSUE THREAD

**Issue by isaqueprofeta** [elastic/mito#61]
Hi, when I try to do a sequential call for login to get a Token and then do a request with the token in the cookie header on my API, it seems that mito are not running the second http request:

```sh
mito -use http,collections,json -insecure=True getlogsfromapi.cel
failed eval: ERROR: <input>:16:5: no such key: Body
 | ).as(token,
 | ....^
```

```go
bytes(
    request("POST",
        "https://mysite/api/login",
        {"username":"myusername", "password":"mypassword"}}}.encode_json()
    ).Body
).as(token,
    request("GET",
        "https://mysite/api/queryendpoint?query-filter=and(ge(timeStamp,'2024-04-30T7'))"
    ).with(
        {"Header":{"Cookie": ["Login="+string(token)],}}
        ).as(resp,
            bytes(resp.Body).decode_json().as(logs,
                {"logs": logs}
            )
        )
)
```

**Comment by efd6** [comment]
The `request` function does not perform a request, it [constructs the details of the request](https://pkg.go.dev/github.com/elastic/mito/lib#hdr-Request). You will need to call [`do_request`](https://pkg.go.dev/github.com/elastic/mito/lib#hdr-Do_Request) on the value that it returns. The API is modeled on the Go [net/http](https://pkg.go.dev/net/http) standard library package, so it might be worthwhile checking that out if you are not already aware of it.

**Comment by isaqueprofeta** [comment]
Oh hey, thanks for the answer... it's different depending on position and chain... and isn't "so clear" when to use do_request() looking at the snippets right now. 

Using the references, I was able to see the full chain working with the code bellow (On the code I've also needed to mess it up with decode_json_stream() to be able to convert my json first response in a type compatible with the collate() function to filter out the session token.)

```go
request("POST",
    "https://myinstance/api/aaaLogin.json",
    {"aaaUser":{"attributes":{"name":"myuser", "pwd":"mypwd"}}}.encode_json()
).do_request().as(resp_token,
    bytes(resp_token.Body).decode_json_stream().as(token,
        request("GET",
            "https://myinstance/api/node/class/acllogDropL3Pkt.json?query-target-filter=and(ge(acllogDropL3Pkt.timeStamp,\"2024-05-08T7\"))"
        ).with({"Header":{"Cookie": ["APIC-cookie="+string(token.collate("imdata.aaaLogin.attributes.token")[0])],}}).do_request().as(resp,
            bytes(resp.Body).decode_json().as(logs,
                {"logs": logs}
            )
        )
    )
)
```

And as a little feedback, I probably going to drop mito and Custom API with Cel Integration for now. First, the time library don't got Add time functions and don't got the custom formating for the needs of my case (Cisco's crazy stuff), and from the current state of the docs (Integrations site, Filebeat and the API here), it's really too much of a steep learning curve for me right now. (FYI: In my scenario I used a Custom API pointing to a localhost FastAPI app to do the auth for elastic and keep the time filter right).

Thank you again for the help and I'll keep looking for updates on the integration and on this project.

**Comment by efd6** [comment]
> it's different depending on position and chain... and isn't "so clear" when to use do_request() looking at the snippets right now.

From the code that you've posted, both steps are making a request and then calling `do_request` on it, though in the second case you are modifying the request to add the headers.

> First, the time library don't got Add time functions

Time values support arithmetic operations, so `t + d` behaves as you would expect; add the duration `d` to the time `t`.

> don't got the custom formating for the needs of my case

String concatenation will allow you to format arbitrary string values and JSON can be constructed using extensions that we provide.

**Comment by isaqueprofeta** [comment]
About the "position and chain" that I told before, is because the first request inside bytes automatically triggers the do_request(), and the examples on request.txt don't use the do_request https://github.com/elastic/mito/blob/dev/testdata/request.txt#L5-L14

After some work and try I found a complete answer for my case, which I share bellow:

```go
request("POST",
    state.url+"/aaaLogin.json",
    {"aaaUser":{"attributes":{"name":"USER", "pwd":"PASSWD"}}}.encode_json()
).do_request().as(resp_token,
    bytes(resp_token.Body).decode_json_stream().as(token,
        request("GET",
            state.url+"/node/class/acllogDropL3Pkt.json?query-target-filter=and(ge(acllogDropL3Pkt.timeStamp,\""+string(now()-duration('1h')).split(':')[0]+"\"))"
        ).with({"Header":{"Cookie": ["APIC-cookie="+string(token.collate("imdata.aaaLogin.attributes.token")[0])],}}).do_request().as(resp,
            bytes(resp.Body).as(logs,
                {"events": logs.decode_json_stream().collate("imdata.acllogDropL3Pkt.attributes")}
            )
        )
    )
)
```

Thx for all the help.

**Comment by efd6** [comment]
I recommend using `now` rather than `now()`. The difference is that `now` is the time that the evaluation started and will be the same for all evaluations for each run, while `now()` is evaluated at the call site. In the situation that you are using it, this will not be different since it's only being called once, but if you are ever doing something where time stamps must agree (for example in some authentication protocols), this will cause problems. So, not a problem here, but something to be aware of.
